version: '3'
services:
  web: &web
    image: ${WEB_IMAGE}
    container_name: app_name
    command: server
    environment:
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ENV: development
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    expose:
      - "3000"

  postgres:
    image: postgres:13.1-alpine
    container_name: app-database
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    env_file: .env
    volumes:
      # - ${DATA_PATH}/sql-data:/docker-entrypoint-initdb.d # comment this line if database import is not needed
      - ${DATA_PATH}/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    expose:
      - "5432"

  app-migration:
    image: ${WEB_IMAGE}
    container_name: app-migration
    environment:
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ENV: development
    env_file: .env
    depends_on:
      - web
      - postgres
    command: install

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  worker:
    <<: *web
    command: worker
    container_name: app-worker
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}/
      QUEUE: "*"
    ports: []
  
  scheduler:
    <<: *web
    container_name: app-scheduler
    command: scheduler
    ports: []

  redis:
    image: redis
    container_name: app-redis
    ports:
    - "6379"
    expose:
      - "6379"
    volumes:
      - ${DATA_PATH}/redis-data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ${DATA_PATH}/pgadmin-data:/var/lib/pgadmin
    restart: always

volumes:
  postgres-data-13:
  redis:

